
export const login = async(req:Request, res:Response):Promise<void> => {
    try {

    }catch(err:Error | unknown){
        
    }
}

// export const updateSelf = async(req:Request, res:Response):Promise<void> => {
//     try {

//     }catch(err:Error | unknown){
        
//     }
// }

// export const deleteUser = async(req:Request, res:Response):Promise<void> => {
//     try {

//     }catch(err:Error | unknown){
        
//     }
// }